#!/usr/bin/env python3

import argparse
import requests
from dataclasses import dataclass
from typing import List, Optional
from google.transit import gtfs_realtime_pb2
import time

parser = argparse.ArgumentParser(description="NYC MTA Subway Train Tracker")
route_ids = ['1', '2', '3', '4', '5', '6', '6X', '7', '7X', 'GS', 'A', 'B', 'C', 'D', 'E', 'F', 'FX', 'FS', 'G', 'J', 'L', 'M', 'N', 'Q', 'R', 'H', 'W', 'Z', 'SI']
parser.add_argument('-r', '--route', type=str, choices=route_ids, default='6', help='Subway route to track')
parser.add_argument('-st', '--self-test', action='store_true', help='Run self-test to display route colors and names')
args = parser.parse_args()

line_to_long_name = {
    "1": "Broadway - 7 Avenue Local",
    "2": "7 Avenue Express",
    "3": "7 Avenue Express",
    "4": "Lexington Avenue Express",
    "5": "Lexington Avenue Express",
    "5X": "Lexington Avenue Express",
    "6": "Lexington Avenue Local",
    "6X": "Pelham Bay Park Express",
    "7": "Flushing Local",
    "7X": "Flushing Express",
    "GS": "42 St Shuttle",
    "A": "8 Avenue Express",
    "B": "6 Avenue Express",
    "C": "8 Avenue Local",
    "D": "6 Avenue Express",
    "E": "8 Avenue Local",
    "F": "Queens Blvd Express/ 6 Av Local",
    "FX": "Brooklyn F Express",
    "FS": "Franklin Avenue Shuttle",
    "G": "Brooklyn-Queens Crosstown",
    "J": "Nassau St Local",
    "L": "14 St-Canarsie Local",
    "M": "Queens Blvd Local/6 Av Local",
    "N": "Broadway Local",
    "Q": "Broadway Express",
    "R": "Broadway Local",
    "H": "Rockaway Park Shuttle",
    "W": "Broadway Local",
    "Z": "Nassau St Express",
    "SI": "Staten Island Railway"
}
directions = {
    "1": (0, -1),
    "2": (0, -1),
    "3": (0, -1),
    "4": (0, -1),
    "5": (0, -1),
    "5X": (0, -1),
    "6": (0, -1),
    "6X": (0, -1),
    "7": (0, -1),
    "7X": (0, -1),
    "GS": (0, -1),
    "A": (0, -1),
    "B": (0, -1),
    "C": (0, -1),
    "D": (0, -1),
    "E": (0, -1),
    "F": (0, -1),
    "FX": (0, -1),
    "FS": (0, -1),
    "G": (0, -1),
    "J": (0, -1),
    "L": (0, -1),
    "M": (0, -1),
    "N": (0, -1),
    "Q": (0, -1),
    "R": (0, -1),
    "H": (0, -1),
    "W": (0, -1),
    "Z": (0, -1),
    "SI": (0, -1)
}
colors = {
    "1": "\033[1m\033[38;2;255;255;255m\033[48;2;216;34;51m",
    "2": "\033[1m\033[38;2;255;255;255m\033[48;2;216;34;51m",
    "3": "\033[1m\033[38;2;255;255;255m\033[48;2;216;34;51m",
    "4": "\033[1m\033[38;2;255;255;255m\033[48;2;0;153;82m",
    "5": "\033[1m\033[38;2;255;255;255m\033[48;2;0;153;82m",
    "5X": "\033[1m\033[38;2;255;255;255m\033[48;2;0;153;82m",
    "6": "\033[1m\033[38;2;255;255;255m\033[48;2;0;153;82m",
    "6X": "\033[1m\033[38;2;255;255;255m\033[48;2;0;153;82m",
    "7": "\033[1m\033[38;2;255;255;255m\033[48;2;154;56;161m",
    "7X": "\033[1m\033[38;2;255;255;255m\033[48;2;154;56;161m",
    "GS": "\033[1m\033[38;2;255;255;255m\033[48;2;124;133;140m",
    "A": "\033[1m\033[38;2;255;255;255m\033[48;2;0;98;207m",
    "B": "\033[1m\033[38;2;255;255;255m\033[48;2;235;104;0m",
    "C": "\033[1m\033[38;2;255;255;255m\033[48;2;0;98;207m",
    "D": "\033[1m\033[38;2;255;255;255m\033[48;2;235;104;0m",
    "E": "\033[1m\033[38;2;255;255;255m\033[48;2;0;98;207m",
    "F": "\033[1m\033[38;2;255;255;255m\033[48;2;235;104;0m",
    "FX": "\033[1m\033[38;2;255;255;255m\033[48;2;235;104;0m",
    "FS": "\033[1m\033[38;2;255;255;255m\033[48;2;124;133;140m",
    "G": "\033[1m\033[38;2;255;255;255m\033[48;2;121;149;52m",
    "J": "\033[1m\033[38;2;255;255;255m\033[48;2;142;92;51m",
    "L": "\033[1m\033[38;2;255;255;255m\033[48;2;124;133;140m",
    "M": "\033[1m\033[38;2;255;255;255m\033[48;2;235;104;0m",
    "N": "\033[1m\033[38;2;0;0;0m\033[48;2;246;188;38m",
    "Q": "\033[1m\033[38;2;0;0;0m\033[48;2;246;188;38m",
    "R": "\033[1m\033[38;2;0;0;0m\033[48;2;246;188;38m",
    "H": "\033[1m\033[38;2;255;255;255m\033[48;2;124;133;140m",
    "W": "\033[1m\033[38;2;0;0;0m\033[48;2;246;188;38m",
    "Z": "\033[1m\033[38;2;255;255;255m\033[48;2;142;92;51m",
    "SI": "\033[1m\033[38;2;255;255;255m\033[48;2;8;23;156m",
}

realtime_feed_urls = {
    "A,C,E,S^R": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace",
    "B,D,F,M,S^F": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-bdfm",
    "G": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-g",
    "J,Z": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-jz",
    "N,Q,R,W": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-nqrw",
    "L": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-l",
    "1,2,3,4,5,6,7,S": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs",
    "SIR": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-si"
}

line_to_url = {
    "1": realtime_feed_urls["1,2,3,4,5,6,7,S"],
    "2": realtime_feed_urls["1,2,3,4,5,6,7,S"],
    "3": realtime_feed_urls["1,2,3,4,5,6,7,S"],
    "4": realtime_feed_urls["1,2,3,4,5,6,7,S"],
    "5": realtime_feed_urls["1,2,3,4,5,6,7,S"],
    "5X": realtime_feed_urls["1,2,3,4,5,6,7,S"],
    "6": realtime_feed_urls["1,2,3,4,5,6,7,S"],
    "6X": realtime_feed_urls["1,2,3,4,5,6,7,S"],
    "7": realtime_feed_urls["1,2,3,4,5,6,7,S"],
    "7X": realtime_feed_urls["1,2,3,4,5,6,7,S"],
    "GS": realtime_feed_urls["1,2,3,4,5,6,7,S"],
    "A": realtime_feed_urls["A,C,E,S^R"],
    "B": realtime_feed_urls["B,D,F,M,S^F"],
    "C": realtime_feed_urls["A,C,E,S^R"],
    "D": realtime_feed_urls["B,D,F,M,S^F"],
    "E": realtime_feed_urls["A,C,E,S^R"],
    "F": realtime_feed_urls["B,D,F,M,S^F"],
    "FX": realtime_feed_urls["B,D,F,M,S^F"],
    "FS": realtime_feed_urls["B,D,F,M,S^F"],
    "G": realtime_feed_urls["G"],
    "J": realtime_feed_urls["J,Z"],
    "L": realtime_feed_urls["L"],
    "M": realtime_feed_urls["B,D,F,M,S^F"],
    "N": realtime_feed_urls["N,Q,R,W"],
    "Q": realtime_feed_urls["N,Q,R,W"],
    "R": realtime_feed_urls["N,Q,R,W"],
    "H": realtime_feed_urls["A,C,E,S^R"],
    "W": realtime_feed_urls["N,Q,R,W"],
    "Z": realtime_feed_urls["J,Z"],
    "SI": realtime_feed_urls["SIR"]
}

@dataclass
class Train:
    trip_id: str
    route_id: str
    start_date: str
    next_stop_id: str
    time_until: float
    direction: Optional[str] = None
    next_station_index: Optional[int] = -1
    direction_char: Optional[str] = None
    vehicle_stop_id: Optional[str] = None
    current_status: Optional[str] = None

    def __str__(self):
        eta = f"{int(self.time_until)}s" if self.time_until is not None else "n/a"
        # vehicle_info = f" | veh_stop: {self.vehicle_stop_id}" if self.vehicle_stop_id else ""
        status_info = f" | {self.current_status}" if self.current_status else ""
        
        # Use the TrainGetter instance to get the station name from the base stop ID
        base_stop_id = self.next_stop_id[:-1] if self.direction_char else self.next_stop_id
        next_station_name = traingetter.station_id_to_name(base_stop_id) or self.next_stop_id
        
        direction_prefix = self.direction_char if self.direction_char else ""

        return f"""
{colors[args.route] + f" {direction_prefix} " + "\033[0m"} {"\033[1;44m" + self.trip_id + "\033[0m"} {"\033[1;33m" + status_info}\n{next_station_name} in {eta}\033[0m"""

def _secs_until(arrival_ts: int) -> float:
    try:
        now = time.time()
        remaining = float(arrival_ts) - now
        return remaining if remaining > 0 else 0.0
    except Exception:
        return 0.0

class TrainGetter():
    def __init__(self) -> None:
        self.stop_id_to_name = {}
        self.name_to_index = {}
        match args.route:
            case '1':
                self.stop_id_to_name = {
                    "101": "Van Cortlandt Park-242 St",
                    "103": "238 St",
                    "104": "231 St",
                    "106": "Marble Hill-225 St",
                    "107": "215 St",
                    "108": "207 St",
                    "109": "Dyckman St",
                    "110": "191 St",
                    "111": "181 St",
                    "112": "168 St-Washington Hts",
                    "113": "157 St",
                    "114": "145 St",
                    "115": "137 St-City College",
                    "116": "125 St",
                    "117": "116 St-Columbia University",
                    "118": "Cathedral Pkwy (110 St)",
                    "119": "103 St",
                    "120": "96 St",
                    "121": "86 St",
                    "122": "79 St",
                    "123": "72 St",
                    "124": "66 St-Lincoln Center",
                    "125": "59 St-Columbus Circle",
                    "126": "50 St",
                    "127": "Times Sq-42 St",
                    "128": "34 St-Penn Station",
                    "129": "28 St",
                    "130": "23 St",
                    "131": "18 St",
                    "132": "14 St",
                    "133": "Christopher St-Stonewall",
                    "134": "Houston St",
                    "135": "Canal St",
                    "136": "Franklin St",
                    "137": "Chambers St",
                    "138": "WTC Cortlandt",
                    "139": "Rector St",
                    "142": "South Ferry",
                }
                self.name_to_index = {
                    "103 St": 21,
                    "116 St-Columbia University": 23,
                    "125 St": 24,
                    "137 St-City College": 25,
                    "14 St": 8,
                    "145 St": 26,
                    "157 St": 27,
                    "168 St-Washington Hts": 28,
                    "18 St": 9,
                    "181 St": 29,
                    "191 St": 30,
                    "207 St": 32,
                    "215 St": 33,
                    "23 St": 10,
                    "231 St": 35,
                    "238 St": 36,
                    "28 St": 11,
                    "34 St-Penn Station": 12,
                    "50 St": 14,
                    "59 St-Columbus Circle": 15,
                    "66 St-Lincoln Center": 16,
                    "72 St": 17,
                    "79 St": 18,
                    "86 St": 19,
                    "96 St": 20,
                    "Canal St": 5,
                    "Cathedral Pkwy (110 St)": 22,
                    "Chambers St": 3,
                    "Christopher St-Stonewall": 7,
                    "Dyckman St": 31,
                    "Franklin St": 4,
                    "Houston St": 6,
                    "Marble Hill-225 St": 34,
                    "Rector St": 1,
                    "South Ferry": 0,
                    "Times Sq-42 St": 13,
                    "Van Cortlandt Park-242 St": 37,
                    "WTC Cortlandt": 2,
                }
            case '2':
                self.stop_id_to_name = {
                    "120": "96 St",
                    "121": "86 St",
                    "122": "79 St",
                    "123": "72 St",
                    "124": "66 St-Lincoln Center",
                    "125": "59 St-Columbus Circle",
                    "126": "50 St",
                    "127": "Times Sq-42 St",
                    "128": "34 St-Penn Station",
                    "129": "28 St",
                    "130": "23 St",
                    "131": "18 St",
                    "132": "14 St",
                    "133": "Christopher St-Stonewall",
                    "134": "Houston St",
                    "135": "Canal St",
                    "136": "Franklin St",
                    "137": "Chambers St",
                    "201": "Wakefield-241 St",
                    "204": "Nereid Av",
                    "205": "233 St",
                    "206": "225 St",
                    "207": "219 St",
                    "208": "Gun Hill Rd",
                    "209": "Burke Av",
                    "210": "Allerton Av",
                    "211": "Pelham Pkwy",
                    "212": "Bronx Park East",
                    "213": "E 180 St",
                    "214": "West Farms Sq-E Tremont Av",
                    "215": "174 St",
                    "216": "Freeman St",
                    "217": "Simpson St",
                    "218": "Intervale Av",
                    "219": "Prospect Av",
                    "220": "Jackson Av",
                    "221": "3 Av-149 St",
                    "222": "149 St-Grand Concourse",
                    "224": "135 St",
                    "225": "125 St",
                    "226": "116 St",
                    "227": "110 St-Malcolm X Plaza",
                    "228": "Park Place",
                    "229": "Fulton St",
                    "230": "Wall St",
                    "231": "Clark St",
                    "232": "Borough Hall",
                    "233": "Hoyt St",
                    "234": "Nevins St",
                    "235": "Atlantic Av-Barclays Ctr",
                    "236": "Bergen St",
                    "237": "Grand Army Plaza",
                    "238": "Eastern Pkwy-Brooklyn Museum",
                    "239": "Franklin Av-Medgar Evers College",
                    "241": "President St-Medgar Evers College",
                    "242": "Sterling St",
                    "243": "Winthrop St",
                    "244": "Church Av",
                    "245": "Beverly Rd",
                    "246": "Newkirk Av-Little Haiti",
                    "247": "Flatbush Av-Brooklyn College",
                }
                self.name_to_index = {
                    "110 St-Malcolm X Plaza": 37,
                    "116 St": 38,
                    "125 St": 39,
                    "135 St": 40,
                    "14 St": 24,
                    "149 St-Grand Concourse": 41,
                    "174 St": 48,
                    "18 St": 25,
                    "219 St": 56,
                    "225 St": 57,
                    "23 St": 26,
                    "233 St": 58,
                    "28 St": 27,
                    "3 Av-149 St": 42,
                    "34 St-Penn Station": 28,
                    "50 St": 30,
                    "59 St-Columbus Circle": 31,
                    "66 St-Lincoln Center": 32,
                    "72 St": 33,
                    "79 St": 34,
                    "86 St": 35,
                    "96 St": 36,
                    "Allerton Av": 53,
                    "Atlantic Av-Barclays Ctr": 11,
                    "Bergen St": 10,
                    "Beverly Rd": 2,
                    "Borough Hall": 14,
                    "Bronx Park East": 51,
                    "Burke Av": 54,
                    "Canal St": 21,
                    "Chambers St": 19,
                    "Christopher St-Stonewall": 23,
                    "Church Av": 3,
                    "Clark St": 15,
                    "E 180 St": 50,
                    "Eastern Pkwy-Brooklyn Museum": 8,
                    "Flatbush Av-Brooklyn College": 0,
                    "Franklin Av-Medgar Evers College": 7,
                    "Franklin St": 20,
                    "Freeman St": 47,
                    "Fulton St": 17,
                    "Grand Army Plaza": 9,
                    "Gun Hill Rd": 55,
                    "Houston St": 22,
                    "Hoyt St": 13,
                    "Intervale Av": 45,
                    "Jackson Av": 43,
                    "Nereid Av": 59,
                    "Nevins St": 12,
                    "Newkirk Av-Little Haiti": 1,
                    "Park Place": 18,
                    "Pelham Pkwy": 52,
                    "President St-Medgar Evers College": 6,
                    "Prospect Av": 44,
                    "Simpson St": 46,
                    "Sterling St": 5,
                    "Times Sq-42 St": 29,
                    "Wakefield-241 St": 60,
                    "Wall St": 16,
                    "West Farms Sq-E Tremont Av": 49,
                    "Winthrop St": 4,
                }
            case '3':
                self.stop_id_to_name = {
                    "120": "96 St",
                    "123": "72 St",
                    "127": "Times Sq-42 St",
                    "128": "34 St-Penn Station",
                    "132": "14 St",
                    "137": "Chambers St",
                    "224": "135 St",
                    "225": "125 St",
                    "226": "116 St",
                    "227": "110 St-Malcolm X Plaza",
                    "228": "Park Place",
                    "229": "Fulton St",
                    "230": "Wall St",
                    "231": "Clark St",
                    "232": "Borough Hall",
                    "233": "Hoyt St",
                    "234": "Nevins St",
                    "235": "Atlantic Av-Barclays Ctr",
                    "236": "Bergen St",
                    "237": "Grand Army Plaza",
                    "238": "Eastern Pkwy-Brooklyn Museum",
                    "239": "Franklin Av-Medgar Evers College",
                    "248": "Nostrand Av",
                    "249": "Kingston Av",
                    "250": "Crown Hts-Utica Av",
                    "251": "Sutter Av-Rutland Rd",
                    "252": "Saratoga Av",
                    "253": "Rockaway Av",
                    "254": "Junius St",
                    "255": "Pennsylvania Av",
                    "256": "Van Siclen Av",
                    "257": "New Lots Av",
                    "301": "Harlem-148 St",
                    "302": "145 St",
                }
                self.name_to_index = {
                    "110 St-Malcolm X Plaza": 28,
                    "116 St": 29,
                    "125 St": 30,
                    "135 St": 31,
                    "14 St": 23,
                    "145 St": 32,
                    "34 St-Penn Station": 24,
                    "72 St": 26,
                    "96 St": 27,
                    "Atlantic Av-Barclays Ctr": 14,
                    "Bergen St": 13,
                    "Borough Hall": 17,
                    "Chambers St": 22,
                    "Clark St": 18,
                    "Crown Hts-Utica Av": 7,
                    "Eastern Pkwy-Brooklyn Museum": 11,
                    "Franklin Av-Medgar Evers College": 10,
                    "Fulton St": 20,
                    "Grand Army Plaza": 12,
                    "Harlem-148 St": 33,
                    "Hoyt St": 16,
                    "Junius St": 3,
                    "Kingston Av": 8,
                    "Nevins St": 15,
                    "New Lots Av": 0,
                    "Nostrand Av": 9,
                    "Park Place": 21,
                    "Pennsylvania Av": 2,
                    "Rockaway Av": 4,
                    "Saratoga Av": 5,
                    "Sutter Av-Rutland Rd": 6,
                    "Times Sq-42 St": 25,
                    "Van Siclen Av": 1,
                    "Wall St": 19,
                }
            case '4':
                self.stop_id_to_name = {
                    "234": "Nevins St",
                    "235": "Atlantic Av-Barclays Ctr",
                    "236": "Bergen St",
                    "237": "Grand Army Plaza",
                    "238": "Eastern Pkwy-Brooklyn Museum",
                    "239": "Franklin Av-Medgar Evers College",
                    "248": "Nostrand Av",
                    "249": "Kingston Av",
                    "250": "Crown Hts-Utica Av",
                    "251": "Sutter Av-Rutland Rd",
                    "252": "Saratoga Av",
                    "253": "Rockaway Av",
                    "254": "Junius St",
                    "255": "Pennsylvania Av",
                    "256": "Van Siclen Av",
                    "257": "New Lots Av",
                    "401": "Woodlawn",
                    "402": "Mosholu Pkwy",
                    "405": "Bedford Park Blvd-Lehman College",
                    "406": "Kingsbridge Rd",
                    "407": "Fordham Rd",
                    "408": "183 St",
                    "409": "Burnside Av",
                    "410": "176 St",
                    "411": "Mt Eden Av",
                    "412": "170 St",
                    "413": "167 St",
                    "414": "161 St-Yankee Stadium",
                    "415": "149 St-Grand Concourse",
                    "416": "138 St-Grand Concourse",
                    "418": "Fulton St",
                    "419": "Wall St",
                    "420": "Bowling Green",
                    "423": "Borough Hall",
                    "621": "125 St",
                    "622": "116 St",
                    "623": "110 St",
                    "624": "103 St",
                    "625": "96 St",
                    "626": "86 St",
                    "627": "77 St",
                    "628": "68 St-Hunter College",
                    "629": "59 St",
                    "630": "51 St",
                    "631": "Grand Central-42 St",
                    "632": "33 St",
                    "633": "28 St",
                    "634": "23 St",
                    "635": "14 St-Union Sq",
                    "636": "Astor Pl",
                    "637": "Bleecker St",
                    "638": "Spring St",
                    "639": "Canal St",
                    "640": "Brooklyn Bridge-City Hall",
                }
                self.name_to_index = {
                    "103 St": 36,
                    "110 St": 37,
                    "116 St": 38,
                    "125 St": 39,
                    "138 St-Grand Concourse": 40,
                    "14 St-Union Sq": 25,
                    "149 St-Grand Concourse": 41,
                    "161 St-Yankee Stadium": 42,
                    "167 St": 43,
                    "170 St": 44,
                    "176 St": 46,
                    "183 St": 48,
                    "23 St": 26,
                    "28 St": 27,
                    "33 St": 28,
                    "51 St": 30,
                    "59 St": 31,
                    "68 St-Hunter College": 32,
                    "77 St": 33,
                    "86 St": 34,
                    "96 St": 35,
                    "Astor Pl": 24,
                    "Atlantic Av-Barclays Ctr": 14,
                    "Bedford Park Blvd-Lehman College": 51,
                    "Bergen St": 13,
                    "Bleecker St": 23,
                    "Borough Hall": 16,
                    "Bowling Green": 17,
                    "Brooklyn Bridge-City Hall": 20,
                    "Burnside Av": 47,
                    "Canal St": 21,
                    "Crown Hts-Utica Av": 7,
                    "Eastern Pkwy-Brooklyn Museum": 11,
                    "Fordham Rd": 49,
                    "Franklin Av-Medgar Evers College": 10,
                    "Fulton St": 19,
                    "Grand Army Plaza": 12,
                    "Grand Central-42 St": 29,
                    "Junius St": 3,
                    "Kingsbridge Rd": 50,
                    "Kingston Av": 8,
                    "Mosholu Pkwy": 52,
                    "Mt Eden Av": 45,
                    "Nevins St": 15,
                    "New Lots Av": 0,
                    "Nostrand Av": 9,
                    "Pennsylvania Av": 2,
                    "Rockaway Av": 4,
                    "Saratoga Av": 5,
                    "Spring St": 22,
                    "Sutter Av-Rutland Rd": 6,
                    "Van Siclen Av": 1,
                    "Wall St": 18,
                    "Woodlawn": 53,
                }
            case '5':
                self.stop_id_to_name = {
                    "213": "E 180 St",
                    "214": "West Farms Sq-E Tremont Av",
                    "215": "174 St",
                    "216": "Freeman St",
                    "217": "Simpson St",
                    "218": "Intervale Av",
                    "219": "Prospect Av",
                    "220": "Jackson Av",
                    "221": "3 Av-149 St",
                    "222": "149 St-Grand Concourse",
                    "234": "Nevins St",
                    "235": "Atlantic Av-Barclays Ctr",
                    "239": "Franklin Av-Medgar Evers College",
                    "248": "Nostrand Av",
                    "249": "Kingston Av",
                    "250": "Crown Hts-Utica Av",
                    "251": "Sutter Av-Rutland Rd",
                    "252": "Saratoga Av",
                    "253": "Rockaway Av",
                    "254": "Junius St",
                    "255": "Pennsylvania Av",
                    "256": "Van Siclen Av",
                    "257": "New Lots Av",
                    "416": "138 St-Grand Concourse",
                    "418": "Fulton St",
                    "419": "Wall St",
                    "420": "Bowling Green",
                    "423": "Borough Hall",
                    "501": "Eastchester-Dyre Av",
                    "502": "Baychester Av",
                    "503": "Gun Hill Rd",
                    "504": "Pelham Pkwy",
                    "505": "Morris Park",
                    "621": "125 St",
                    "626": "86 St",
                    "629": "59 St",
                    "631": "Grand Central-42 St",
                    "635": "14 St-Union Sq",
                    "640": "Brooklyn Bridge-City Hall",
                }
                self.name_to_index = {
                    "125 St": 22,
                    "138 St-Grand Concourse": 23,
                    "14 St-Union Sq": 18,
                    "149 St-Grand Concourse": 24,
                    "174 St": 31,
                    "3 Av-149 St": 25,
                    "59 St": 20,
                    "86 St": 21,
                    "Atlantic Av-Barclays Ctr": 11,
                    "Baychester Av": 37,
                    "Borough Hall": 13,
                    "Bowling Green": 14,
                    "Brooklyn Bridge-City Hall": 17,
                    "Crown Hts-Utica Av": 7,
                    "E 180 St": 33,
                    "Eastchester-Dyre Av": 38,
                    "Franklin Av-Medgar Evers College": 10,
                    "Freeman St": 30,
                    "Fulton St": 16,
                    "Grand Central-42 St": 19,
                    "Gun Hill Rd": 36,
                    "Intervale Av": 28,
                    "Jackson Av": 26,
                    "Junius St": 3,
                    "Kingston Av": 8,
                    "Morris Park": 34,
                    "Nevins St": 12,
                    "New Lots Av": 0,
                    "Nostrand Av": 9,
                    "Pelham Pkwy": 35,
                    "Pennsylvania Av": 2,
                    "Prospect Av": 27,
                    "Rockaway Av": 4,
                    "Saratoga Av": 5,
                    "Simpson St": 29,
                    "Sutter Av-Rutland Rd": 6,
                    "Van Siclen Av": 1,
                    "Wall St": 15,
                    "West Farms Sq-E Tremont Av": 32,
                }
            case '6':
                self.stop_id_to_name = {
                    "601": "Pelham Bay Park",
                    "602": "Buhre Av",
                    "603": "Middletown Rd",
                    "604": "Westchester Sq-E Tremont Av",
                    "606": "Zerega Av",
                    "607": "Castle Hill Av",
                    "608": "Parkchester",
                    "609": "St Lawrence Av",
                    "610": "Morrison Av-Soundview",
                    "611": "Elder Av",
                    "612": "Whitlock Av",
                    "613": "Hunts Point Av",
                    "614": "Longwood Av",
                    "615": "E 149 St",
                    "616": "E 143 St-St Mary's St",
                    "617": "Cypress Av",
                    "618": "Brook Av",
                    "619": "3 Av-138 St",
                    "621": "125 St",
                    "622": "116 St",
                    "623": "110 St",
                    "624": "103 St",
                    "625": "96 St",
                    "626": "86 St",
                    "627": "77 St",
                    "628": "68 St-Hunter College",
                    "629": "59 St",
                    "630": "51 St",
                    "631": "Grand Central-42 St",
                    "632": "33 St",
                    "633": "28 St",
                    "634": "23 St",
                    "635": "14 St-Union Sq",
                    "636": "Astor Pl",
                    "637": "Bleecker St",
                    "638": "Spring St",
                    "639": "Canal St",
                    "640": "Brooklyn Bridge-City Hall",
                }
                self.name_to_index = {
                    "103 St": 16,
                    "110 St": 17,
                    "116 St": 18,
                    "125 St": 19,
                    "14 St-Union Sq": 5,
                    "23 St": 6,
                    "28 St": 7,
                    "3 Av-138 St": 20,
                    "33 St": 8,
                    "51 St": 10,
                    "59 St": 11,
                    "68 St-Hunter College": 12,
                    "77 St": 13,
                    "86 St": 14,
                    "96 St": 15,
                    "Astor Pl": 4,
                    "Bleecker St": 3,
                    "Brook Av": 21,
                    "Brooklyn Bridge-City Hall": 0,
                    "Buhre Av": 36,
                    "Canal St": 1,
                    "Castle Hill Av": 32,
                    "Cypress Av": 22,
                    "E 143 St-St Mary's St": 23,
                    "E 149 St": 24,
                    "Elder Av": 28,
                    "Grand Central-42 St": 9,
                    "Hunts Point Av": 26,
                    "Longwood Av": 25,
                    "Middletown Rd": 35,
                    "Morrison Av-Soundview": 29,
                    "Parkchester": 31,
                    "Pelham Bay Park": 37,
                    "Spring St": 2,
                    "St Lawrence Av": 30,
                    "Westchester Sq-E Tremont Av": 34,
                    "Whitlock Av": 27,
                    "Zerega Av": 33,
                }
            case '6X':
                self.stop_id_to_name = {
                    "601": "Pelham Bay Park",
                    "602": "Buhre Av",
                    "603": "Middletown Rd",
                    "604": "Westchester Sq-E Tremont Av",
                    "606": "Zerega Av",
                    "607": "Castle Hill Av",
                    "608": "Parkchester",
                    "613": "Hunts Point Av",
                    "619": "3 Av-138 St",
                    "621": "125 St",
                    "622": "116 St",
                    "623": "110 St",
                    "624": "103 St",
                    "625": "96 St",
                    "626": "86 St",
                    "627": "77 St",
                    "628": "68 St-Hunter College",
                    "629": "59 St",
                    "630": "51 St",
                    "631": "Grand Central-42 St",
                    "632": "33 St",
                    "633": "28 St",
                    "634": "23 St",
                    "635": "14 St-Union Sq",
                    "636": "Astor Pl",
                    "637": "Bleecker St",
                    "638": "Spring St",
                    "639": "Canal St",
                    "640": "Brooklyn Bridge-City Hall",
                }
                self.name_to_index = {
                    "103 St": 16,
                    "110 St": 17,
                    "116 St": 18,
                    "125 St": 19,
                    "14 St-Union Sq": 5,
                    "23 St": 6,
                    "28 St": 7,
                    "3 Av-138 St": 20,
                    "33 St": 8,
                    "51 St": 10,
                    "59 St": 11,
                    "68 St-Hunter College": 12,
                    "77 St": 13,
                    "86 St": 14,
                    "96 St": 15,
                    "Astor Pl": 4,
                    "Bleecker St": 3,
                    "Brooklyn Bridge-City Hall": 0,
                    "Buhre Av": 27,
                    "Canal St": 1,
                    "Castle Hill Av": 23,
                    "Grand Central-42 St": 9,
                    "Hunts Point Av": 21,
                    "Middletown Rd": 26,
                    "Parkchester": 22,
                    "Pelham Bay Park": 28,
                    "Spring St": 2,
                    "Westchester Sq-E Tremont Av": 25,
                    "Zerega Av": 24,
                }
            case '7':
                self.stop_id_to_name = {
                    "701": "Flushing-Main St",
                    "702": "Mets-Willets Point",
                    "705": "111 St",
                    "706": "103 St-Corona Plaza",
                    "707": "Junction Blvd",
                    "708": "90 St-Elmhurst Av",
                    "709": "82 St-Jackson Hts",
                    "710": "74 St-Broadway",
                    "711": "69 St",
                    "712": "61 St-Woodside",
                    "713": "52 St",
                    "714": "46 St-Bliss St",
                    "715": "40 St-Lowery St",
                    "716": "33 St-Rawson St",
                    "718": "Queensboro Plaza",
                    "719": "Court Sq",
                    "720": "Hunters Point Av",
                    "721": "Vernon Blvd-Jackson Av",
                    "723": "Grand Central-42 St",
                    "724": "5 Av",
                    "725": "Times Sq-42 St",
                    "726": "34 St-Hudson Yards",
                }
                self.name_to_index = {
                    "103 St-Corona Plaza": 18,
                    "111 St": 19,
                    "33 St-Rawson St": 8,
                    "34 St-Hudson Yards": 0,
                    "40 St-Lowery St": 9,
                    "46 St-Bliss St": 10,
                    "5 Av": 2,
                    "52 St": 11,
                    "61 St-Woodside": 12,
                    "69 St": 13,
                    "74 St-Broadway": 14,
                    "82 St-Jackson Hts": 15,
                    "90 St-Elmhurst Av": 16,
                    "Court Sq": 6,
                    "Flushing-Main St": 21,
                    "Grand Central-42 St": 3,
                    "Hunters Point Av": 5,
                    "Junction Blvd": 17,
                    "Mets-Willets Point": 20,
                    "Queensboro Plaza": 7,
                    "Times Sq-42 St": 1,
                    "Vernon Blvd-Jackson Av": 4,
                }
            case '7X':
                self.stop_id_to_name = {
                    "701": "Flushing-Main St",
                    "702": "Mets-Willets Point",
                    "707": "Junction Blvd",
                    "710": "74 St-Broadway",
                    "711": "69 St",
                    "712": "61 St-Woodside",
                    "713": "52 St",
                    "714": "46 St-Bliss St",
                    "715": "40 St-Lowery St",
                    "716": "33 St-Rawson St",
                    "718": "Queensboro Plaza",
                    "719": "Court Sq",
                    "720": "Hunters Point Av",
                    "721": "Vernon Blvd-Jackson Av",
                    "723": "Grand Central-42 St",
                    "724": "5 Av",
                    "725": "Times Sq-42 St",
                    "726": "34 St-Hudson Yards",
                }
                self.name_to_index = {
                    "33 St-Rawson St": 8,
                    "34 St-Hudson Yards": 0,
                    "40 St-Lowery St": 9,
                    "46 St-Bliss St": 10,
                    "5 Av": 2,
                    "52 St": 11,
                    "61 St-Woodside": 12,
                    "69 St": 13,
                    "74 St-Broadway": 14,
                    "Court Sq": 6,
                    "Flushing-Main St": 17,
                    "Grand Central-42 St": 3,
                    "Hunters Point Av": 5,
                    "Junction Blvd": 15,
                    "Mets-Willets Point": 16,
                    "Queensboro Plaza": 7,
                    "Times Sq-42 St": 1,
                    "Vernon Blvd-Jackson Av": 4,
                }
            case 'A':
                self.stop_id_to_name = {
                    "A02": "Inwood-207 St",
                    "A03": "Dyckman St",
                    "A05": "190 St",
                    "A06": "181 St",
                    "A07": "175 St",
                    "A09": "168 St",
                    "A10": "163 St-Amsterdam Av",
                    "A11": "155 St",
                    "A12": "145 St",
                    "A14": "135 St",
                    "A15": "125 St",
                    "A16": "116 St",
                    "A17": "Cathedral Pkwy (110 St)",
                    "A18": "103 St",
                    "A19": "96 St",
                    "A20": "86 St",
                    "A21": "81 St-Museum of Natural History",
                    "A22": "72 St",
                    "A24": "59 St-Columbus Circle",
                    "A25": "50 St",
                    "A27": "42 St-Port Authority Bus Terminal",
                    "A28": "34 St-Penn Station",
                    "A30": "23 St",
                    "A31": "14 St",
                    "A32": "W 4 St-Wash Sq",
                    "A33": "Spring St",
                    "A34": "Canal St",
                    "A36": "Chambers St",
                    "A38": "Fulton St",
                    "A40": "High St",
                    "A41": "Jay St-MetroTech",
                    "A42": "Hoyt-Schermerhorn Sts",
                    "A43": "Lafayette Av",
                    "A44": "Clinton-Washington Avs",
                    "A45": "Franklin Av",
                    "A46": "Nostrand Av",
                    "A47": "Kingston-Throop Avs",
                    "A48": "Utica Av",
                    "A49": "Ralph Av",
                    "A50": "Rockaway Av",
                    "A51": "Broadway Junction",
                    "A52": "Liberty Av",
                    "A53": "Van Siclen Av",
                    "A54": "Shepherd Av",
                    "A55": "Euclid Av",
                    "A57": "Grant Av",
                    "A59": "80 St",
                    "A60": "88 St",
                    "A61": "Rockaway Blvd",
                    "H01": "Aqueduct Racetrack",
                    "H02": "Aqueduct-N Conduit Av",
                    "H03": "Howard Beach-JFK Airport",
                    "H04": "Broad Channel",
                    "H06": "Beach 67 St",
                    "H07": "Beach 60 St",
                    "H08": "Beach 44 St",
                    "H09": "Beach 36 St",
                    "H10": "Beach 25 St",
                    "H11": "Far Rockaway-Mott Av",
                }
                self.name_to_index = {
                    "103 St": 45,
                    "116 St": 47,
                    "125 St": 48,
                    "135 St": 49,
                    "14 St": 35,
                    "145 St": 50,
                    "155 St": 51,
                    "163 St-Amsterdam Av": 52,
                    "168 St": 53,
                    "175 St": 54,
                    "181 St": 55,
                    "190 St": 56,
                    "23 St": 36,
                    "34 St-Penn Station": 37,
                    "42 St-Port Authority Bus Terminal": 38,
                    "50 St": 39,
                    "59 St-Columbus Circle": 40,
                    "72 St": 41,
                    "80 St": 12,
                    "81 St-Museum of Natural History": 42,
                    "86 St": 43,
                    "88 St": 11,
                    "96 St": 44,
                    "Aqueduct Racetrack": 9,
                    "Aqueduct-N Conduit Av": 8,
                    "Beach 25 St": 1,
                    "Beach 36 St": 2,
                    "Beach 44 St": 3,
                    "Beach 60 St": 4,
                    "Beach 67 St": 5,
                    "Broad Channel": 6,
                    "Broadway Junction": 18,
                    "Canal St": 32,
                    "Cathedral Pkwy (110 St)": 46,
                    "Chambers St": 31,
                    "Clinton-Washington Avs": 25,
                    "Dyckman St": 57,
                    "Euclid Av": 14,
                    "Far Rockaway-Mott Av": 0,
                    "Franklin Av": 24,
                    "Fulton St": 30,
                    "Grant Av": 13,
                    "High St": 29,
                    "Howard Beach-JFK Airport": 7,
                    "Hoyt-Schermerhorn Sts": 27,
                    "Inwood-207 St": 58,
                    "Jay St-MetroTech": 28,
                    "Kingston-Throop Avs": 22,
                    "Lafayette Av": 26,
                    "Liberty Av": 17,
                    "Nostrand Av": 23,
                    "Ralph Av": 20,
                    "Rockaway Av": 19,
                    "Rockaway Blvd": 10,
                    "Shepherd Av": 15,
                    "Spring St": 33,
                    "Utica Av": 21,
                    "Van Siclen Av": 16,
                    "W 4 St-Wash Sq": 34,
                }
            case 'B':
                self.stop_id_to_name = {
                    "A14": "135 St",
                    "A15": "125 St",
                    "A16": "116 St",
                    "A17": "Cathedral Pkwy (110 St)",
                    "A18": "103 St",
                    "A19": "96 St",
                    "A20": "86 St",
                    "A21": "81 St-Museum of Natural History",
                    "A22": "72 St",
                    "A24": "59 St-Columbus Circle",
                    "D03": "Bedford Park Blvd",
                    "D04": "Kingsbridge Rd",
                    "D05": "Fordham Rd",
                    "D06": "182-183 Sts",
                    "D07": "Tremont Av",
                    "D08": "174-175 Sts",
                    "D09": "170 St",
                    "D10": "167 St",
                    "D11": "161 St-Yankee Stadium",
                    "D12": "155 St",
                    "D13": "145 St",
                    "D14": "7 Av",
                    "D15": "47-50 Sts-Rockefeller Ctr",
                    "D16": "42 St-Bryant Pk",
                    "D17": "34 St-Herald Sq",
                    "D20": "W 4 St-Wash Sq",
                    "D21": "Broadway-Lafayette St",
                    "D22": "Grand St",
                    "D24": "Atlantic Av-Barclays Ctr",
                    "D25": "7 Av",
                    "D26": "Prospect Park",
                    "D28": "Church Av",
                    "D31": "Newkirk Plaza",
                    "D35": "Kings Hwy",
                    "D39": "Sheepshead Bay",
                    "D40": "Brighton Beach",
                    "R30": "DeKalb Av",
                }
                self.name_to_index = {
                    "103 St": 15,
                    "116 St": 13,
                    "125 St": 12,
                    "135 St": 11,
                    "145 St": 10,
                    "155 St": 9,
                    "161 St-Yankee Stadium": 8,
                    "167 St": 7,
                    "170 St": 6,
                    "174-175 Sts": 5,
                    "182-183 Sts": 3,
                    "34 St-Herald Sq": 24,
                    "42 St-Bryant Pk": 23,
                    "47-50 Sts-Rockefeller Ctr": 22,
                    "59 St-Columbus Circle": 20,
                    "7 Av": 30,
                    "72 St": 19,
                    "81 St-Museum of Natural History": 18,
                    "86 St": 17,
                    "96 St": 16,
                    "Atlantic Av-Barclays Ctr": 29,
                    "Bedford Park Blvd": 0,
                    "Brighton Beach": 36,
                    "Broadway-Lafayette St": 26,
                    "Cathedral Pkwy (110 St)": 14,
                    "Church Av": 32,
                    "DeKalb Av": 28,
                    "Fordham Rd": 2,
                    "Grand St": 27,
                    "Kings Hwy": 34,
                    "Kingsbridge Rd": 1,
                    "Newkirk Plaza": 33,
                    "Prospect Park": 31,
                    "Sheepshead Bay": 35,
                    "Tremont Av": 4,
                    "W 4 St-Wash Sq": 25,
                }
            case 'C':
                self.stop_id_to_name = {
                    "A09": "168 St",
                    "A10": "163 St-Amsterdam Av",
                    "A11": "155 St",
                    "A12": "145 St",
                    "A14": "135 St",
                    "A15": "125 St",
                    "A16": "116 St",
                    "A17": "Cathedral Pkwy (110 St)",
                    "A18": "103 St",
                    "A19": "96 St",
                    "A20": "86 St",
                    "A21": "81 St-Museum of Natural History",
                    "A22": "72 St",
                    "A24": "59 St-Columbus Circle",
                    "A25": "50 St",
                    "A27": "42 St-Port Authority Bus Terminal",
                    "A28": "34 St-Penn Station",
                    "A30": "23 St",
                    "A31": "14 St",
                    "A32": "W 4 St-Wash Sq",
                    "A33": "Spring St",
                    "A34": "Canal St",
                    "A36": "Chambers St",
                    "A38": "Fulton St",
                    "A40": "High St",
                    "A41": "Jay St-MetroTech",
                    "A42": "Hoyt-Schermerhorn Sts",
                    "A43": "Lafayette Av",
                    "A44": "Clinton-Washington Avs",
                    "A45": "Franklin Av",
                    "A46": "Nostrand Av",
                    "A47": "Kingston-Throop Avs",
                    "A48": "Utica Av",
                    "A49": "Ralph Av",
                    "A50": "Rockaway Av",
                    "A51": "Broadway Junction",
                    "A52": "Liberty Av",
                    "A53": "Van Siclen Av",
                    "A54": "Shepherd Av",
                    "A55": "Euclid Av",
                }
                self.name_to_index = {
                    "103 St": 31,
                    "116 St": 33,
                    "125 St": 34,
                    "135 St": 35,
                    "14 St": 21,
                    "145 St": 36,
                    "155 St": 37,
                    "163 St-Amsterdam Av": 38,
                    "168 St": 39,
                    "23 St": 22,
                    "34 St-Penn Station": 23,
                    "42 St-Port Authority Bus Terminal": 24,
                    "50 St": 25,
                    "59 St-Columbus Circle": 26,
                    "72 St": 27,
                    "81 St-Museum of Natural History": 28,
                    "86 St": 29,
                    "96 St": 30,
                    "Broadway Junction": 4,
                    "Canal St": 18,
                    "Cathedral Pkwy (110 St)": 32,
                    "Chambers St": 17,
                    "Clinton-Washington Avs": 11,
                    "Euclid Av": 0,
                    "Franklin Av": 10,
                    "Fulton St": 16,
                    "High St": 15,
                    "Hoyt-Schermerhorn Sts": 13,
                    "Jay St-MetroTech": 14,
                    "Kingston-Throop Avs": 8,
                    "Lafayette Av": 12,
                    "Liberty Av": 3,
                    "Nostrand Av": 9,
                    "Ralph Av": 6,
                    "Rockaway Av": 5,
                    "Shepherd Av": 1,
                    "Spring St": 19,
                    "Utica Av": 7,
                    "Van Siclen Av": 2,
                    "W 4 St-Wash Sq": 20,
                }
            case 'D':
                self.stop_id_to_name = {
                    "A15": "125 St",
                    "A24": "59 St-Columbus Circle",
                    "B12": "9 Av",
                    "B13": "Fort Hamilton Pkwy",
                    "B14": "50 St",
                    "B15": "55 St",
                    "B16": "62 St",
                    "B17": "71 St",
                    "B18": "79 St",
                    "B19": "18 Av",
                    "B20": "20 Av",
                    "B21": "Bay Pkwy",
                    "B22": "25 Av",
                    "B23": "Bay 50 St",
                    "D01": "Norwood-205 St",
                    "D03": "Bedford Park Blvd",
                    "D04": "Kingsbridge Rd",
                    "D05": "Fordham Rd",
                    "D06": "182-183 Sts",
                    "D07": "Tremont Av",
                    "D08": "174-175 Sts",
                    "D09": "170 St",
                    "D10": "167 St",
                    "D11": "161 St-Yankee Stadium",
                    "D12": "155 St",
                    "D13": "145 St",
                    "D14": "7 Av",
                    "D15": "47-50 Sts-Rockefeller Ctr",
                    "D16": "42 St-Bryant Pk",
                    "D17": "34 St-Herald Sq",
                    "D20": "W 4 St-Wash Sq",
                    "D21": "Broadway-Lafayette St",
                    "D22": "Grand St",
                    "D43": "Coney Island-Stillwell Av",
                    "R30": "DeKalb Av",
                    "R31": "Atlantic Av-Barclays Ctr",
                    "R32": "Union St",
                    "R33": "4 Av-9 St",
                    "R34": "Prospect Av",
                    "R35": "25 St",
                    "R36": "36 St",
                }
                self.name_to_index = {
                    "125 St": 28,
                    "145 St": 29,
                    "155 St": 30,
                    "161 St-Yankee Stadium": 31,
                    "167 St": 32,
                    "170 St": 33,
                    "174-175 Sts": 34,
                    "18 Av": 5,
                    "182-183 Sts": 36,
                    "20 Av": 4,
                    "25 Av": 2,
                    "25 St": 14,
                    "34 St-Herald Sq": 23,
                    "36 St": 13,
                    "4 Av-9 St": 16,
                    "42 St-Bryant Pk": 24,
                    "47-50 Sts-Rockefeller Ctr": 25,
                    "50 St": 10,
                    "55 St": 9,
                    "59 St-Columbus Circle": 27,
                    "62 St": 8,
                    "7 Av": 26,
                    "71 St": 7,
                    "79 St": 6,
                    "9 Av": 12,
                    "Atlantic Av-Barclays Ctr": 18,
                    "Bay 50 St": 1,
                    "Bay Pkwy": 3,
                    "Bedford Park Blvd": 39,
                    "Broadway-Lafayette St": 21,
                    "Coney Island-Stillwell Av": 0,
                    "DeKalb Av": 19,
                    "Fordham Rd": 37,
                    "Fort Hamilton Pkwy": 11,
                    "Grand St": 20,
                    "Kingsbridge Rd": 38,
                    "Norwood-205 St": 40,
                    "Prospect Av": 15,
                    "Tremont Av": 35,
                    "Union St": 17,
                    "W 4 St-Wash Sq": 22,
                }
            case 'E':
                self.stop_id_to_name = {
                    "A25": "50 St",
                    "A27": "42 St-Port Authority Bus Terminal",
                    "A28": "34 St-Penn Station",
                    "A30": "23 St",
                    "A31": "14 St",
                    "A32": "W 4 St-Wash Sq",
                    "A33": "Spring St",
                    "A34": "Canal St",
                    "D14": "7 Av",
                    "E01": "World Trade Center",
                    "F05": "Briarwood",
                    "F06": "Kew Gardens-Union Tpke",
                    "F07": "75 Av",
                    "F09": "Court Sq-23 St",
                    "F11": "Lexington Av/53 St",
                    "F12": "5 Av/53 St",
                    "G05": "Jamaica Center-Parsons/Archer",
                    "G06": "Sutphin Blvd-Archer Av-JFK Airport",
                    "G07": "Jamaica-Van Wyck",
                    "G08": "Forest Hills-71 Av",
                    "G09": "67 Av",
                    "G10": "63 Dr-Rego Park",
                    "G11": "Woodhaven Blvd",
                    "G12": "Grand Av-Newtown",
                    "G13": "Elmhurst Av",
                    "G14": "Jackson Hts-Roosevelt Av",
                    "G15": "65 St",
                    "G16": "Northern Blvd",
                    "G18": "46 St",
                    "G19": "Steinway St",
                    "G20": "36 St",
                    "G21": "Queens Plaza",
                }
                self.name_to_index = {
                    "14 St": 4,
                    "23 St": 5,
                    "34 St-Penn Station": 6,
                    "36 St": 14,
                    "42 St-Port Authority Bus Terminal": 7,
                    "46 St": 16,
                    "5 Av/53 St": 10,
                    "50 St": 8,
                    "63 Dr-Rego Park": 23,
                    "65 St": 18,
                    "67 Av": 24,
                    "7 Av": 9,
                    "75 Av": 26,
                    "Briarwood": 28,
                    "Canal St": 1,
                    "Court Sq-23 St": 12,
                    "Elmhurst Av": 20,
                    "Forest Hills-71 Av": 25,
                    "Grand Av-Newtown": 21,
                    "Jackson Hts-Roosevelt Av": 19,
                    "Jamaica Center-Parsons/Archer": 31,
                    "Jamaica-Van Wyck": 29,
                    "Kew Gardens-Union Tpke": 27,
                    "Lexington Av/53 St": 11,
                    "Northern Blvd": 17,
                    "Queens Plaza": 13,
                    "Spring St": 2,
                    "Steinway St": 15,
                    "Sutphin Blvd-Archer Av-JFK Airport": 30,
                    "W 4 St-Wash Sq": 3,
                    "Woodhaven Blvd": 22,
                    "World Trade Center": 0,
                }
            case 'F':
                self.stop_id_to_name = {
                    "A41": "Jay St-MetroTech",
                    "B04": "21 St-Queensbridge",
                    "B06": "Roosevelt Island",
                    "B08": "Lexington Av/63 St",
                    "B10": "57 St",
                    "D15": "47-50 Sts-Rockefeller Ctr",
                    "D16": "42 St-Bryant Pk",
                    "D17": "34 St-Herald Sq",
                    "D18": "23 St",
                    "D19": "14 St",
                    "D20": "W 4 St-Wash Sq",
                    "D21": "Broadway-Lafayette St",
                    "D42": "W 8 St-NY Aquarium",
                    "D43": "Coney Island-Stillwell Av",
                    "F01": "Jamaica-179 St",
                    "F02": "169 St",
                    "F03": "Parsons Blvd",
                    "F04": "Sutphin Blvd",
                    "F05": "Briarwood",
                    "F06": "Kew Gardens-Union Tpke",
                    "F07": "75 Av",
                    "F14": "2 Av",
                    "F15": "Delancey St-Essex St",
                    "F16": "East Broadway",
                    "F18": "York St",
                    "F20": "Bergen St",
                    "F21": "Carroll St",
                    "F22": "Smith-9 Sts",
                    "F23": "4 Av-9 St",
                    "F24": "7 Av",
                    "F25": "15 St-Prospect Park",
                    "F26": "Fort Hamilton Pkwy",
                    "F27": "Church Av",
                    "F29": "Ditmas Av",
                    "F30": "18 Av",
                    "F31": "Avenue I",
                    "F32": "Bay Pkwy",
                    "F33": "Avenue ",
                    "F34": "Avenue P",
                    "F35": "Kings Hwy",
                    "F36": "Avenue U",
                    "F38": "Avenue X",
                    "F39": "Neptune Av",
                    "G08": "Forest Hills-71 Av",
                    "G09": "67 Av",
                    "G10": "63 Dr-Rego Park",
                    "G11": "Woodhaven Blvd",
                    "G12": "Grand Av-Newtown",
                    "G13": "Elmhurst Av",
                    "G14": "Jackson Hts-Roosevelt Av",
                    "G15": "65 St",
                    "G16": "Northern Blvd",
                    "G18": "46 St",
                    "G19": "Steinway St",
                    "G20": "36 St",
                }
                self.name_to_index = {
                    "14 St": 27,
                    "15 St-Prospect Park": 14,
                    "169 St": 53,
                    "18 Av": 10,
                    "2 Av": 24,
                    "21 St-Queensbridge": 35,
                    "23 St": 28,
                    "34 St-Herald Sq": 29,
                    "36 St": 36,
                    "4 Av-9 St": 16,
                    "42 St-Bryant Pk": 30,
                    "46 St": 38,
                    "47-50 Sts-Rockefeller Ctr": 31,
                    "57 St": 32,
                    "63 Dr-Rego Park": 45,
                    "65 St": 40,
                    "67 Av": 46,
                    "7 Av": 15,
                    "75 Av": 48,
                    "Avenue ": 7,
                    "Avenue I": 9,
                    "Avenue P": 6,
                    "Avenue U": 4,
                    "Avenue X": 3,
                    "Bay Pkwy": 8,
                    "Bergen St": 19,
                    "Briarwood": 50,
                    "Broadway-Lafayette St": 25,
                    "Carroll St": 18,
                    "Church Av": 12,
                    "Coney Island-Stillwell Av": 0,
                    "Delancey St-Essex St": 23,
                    "Ditmas Av": 11,
                    "East Broadway": 22,
                    "Elmhurst Av": 42,
                    "Forest Hills-71 Av": 47,
                    "Fort Hamilton Pkwy": 13,
                    "Grand Av-Newtown": 43,
                    "Jackson Hts-Roosevelt Av": 41,
                    "Jamaica-179 St": 54,
                    "Jay St-MetroTech": 20,
                    "Kew Gardens-Union Tpke": 49,
                    "Kings Hwy": 5,
                    "Lexington Av/63 St": 33,
                    "Neptune Av": 2,
                    "Northern Blvd": 39,
                    "Parsons Blvd": 52,
                    "Roosevelt Island": 34,
                    "Smith-9 Sts": 17,
                    "Steinway St": 37,
                    "Sutphin Blvd": 51,
                    "W 4 St-Wash Sq": 26,
                    "Woodhaven Blvd": 44,
                    "York St": 21,
                }
            case 'FS':
                self.stop_id_to_name = {
                    "D26": "Prospect Park",
                    "S01": "Franklin Av",
                    "S03": "Park Pl",
                    "S04": "Botanic Garden",
                }
                self.name_to_index = {
                    "Botanic Garden": 1,
                    "Franklin Av": 3,
                    "Park Pl": 2,
                    "Prospect Park": 0,
                }
            case 'FX':
                self.stop_id_to_name = {
                    "A41": "Jay St-MetroTech",
                    "B04": "21 St-Queensbridge",
                    "B06": "Roosevelt Island",
                    "B08": "Lexington Av/63 St",
                    "B10": "57 St",
                    "D15": "47-50 Sts-Rockefeller Ctr",
                    "D16": "42 St-Bryant Pk",
                    "D17": "34 St-Herald Sq",
                    "D18": "23 St",
                    "D19": "14 St",
                    "D20": "W 4 St-Wash Sq",
                    "D21": "Broadway-Lafayette St",
                    "D42": "W 8 St-NY Aquarium",
                    "D43": "Coney Island-Stillwell Av",
                    "F01": "Jamaica-179 St",
                    "F02": "169 St",
                    "F03": "Parsons Blvd",
                    "F04": "Sutphin Blvd",
                    "F05": "Briarwood",
                    "F06": "Kew Gardens-Union Tpke",
                    "F07": "75 Av",
                    "F14": "2 Av",
                    "F15": "Delancey St-Essex St",
                    "F16": "East Broadway",
                    "F18": "York St",
                    "F24": "7 Av",
                    "F27": "Church Av",
                    "F29": "Ditmas Av",
                    "F30": "18 Av",
                    "F31": "Avenue I",
                    "F32": "Bay Pkwy",
                    "F33": "Avenue ",
                    "F34": "Avenue P",
                    "F35": "Kings Hwy",
                    "F36": "Avenue U",
                    "F38": "Avenue X",
                    "F39": "Neptune Av",
                    "G08": "Forest Hills-71 Av",
                    "G14": "Jackson Hts-Roosevelt Av",
                }
                self.name_to_index = {
                    "14 St": 17,
                    "169 St": 1,
                    "18 Av": 28,
                    "2 Av": 20,
                    "21 St-Queensbridge": 9,
                    "23 St": 16,
                    "34 St-Herald Sq": 15,
                    "42 St-Bryant Pk": 14,
                    "47-50 Sts-Rockefeller Ctr": 13,
                    "57 St": 12,
                    "7 Av": 25,
                    "75 Av": 6,
                    "Avenue ": 31,
                    "Avenue I": 29,
                    "Avenue P": 32,
                    "Avenue U": 34,
                    "Avenue X": 35,
                    "Bay Pkwy": 30,
                    "Briarwood": 4,
                    "Broadway-Lafayette St": 19,
                    "Church Av": 26,
                    "Coney Island-Stillwell Av": 38,
                    "Delancey St-Essex St": 21,
                    "Ditmas Av": 11,
                    "East Broadway": 22,
                    "Elmhurst Av": 42,
                    "Forest Hills-71 Av": 7,
                    "Fort Hamilton Pkwy": 13,
                    "Grand Av-Newtown": 43,
                    "Jackson Hts-Roosevelt Av": 41,
                    "Jamaica-179 St": 0,
                    "Jay St-MetroTech": 24,
                    "Kew Gardens-Union Tpke": 5,
                    "Kings Hwy": 33,
                    "Lexington Av/63 St": 11,
                    "Neptune Av": 36,
                    "Parsons Blvd": 2,
                    "Roosevelt Island": 10,
                    "Sutphin Blvd": 3,
                    "W 4 St-Wash Sq": 18,
                    "Woodhaven Blvd": 23,
                    "York St": 17,
                }
            case 'G':
                self.stop_id_to_name = {
                    "A42": "Hoyt-Schermerhorn Sts",
                    "F20": "Bergen St",
                    "F21": "Carroll St",
                    "F22": "Smith-9 Sts",
                    "F23": "4 Av-9 St",
                    "F24": "7 Av",
                    "F25": "15 St-Prospect Park",
                    "F26": "Fort Hamilton Pkwy",
                    "F27": "Church Av",
                    "G22": "Court Sq",
                    "G24": "21 St",
                    "G26": "Greenpoint Av",
                    "G28": "Nassau Av",
                    "G29": "Metropolitan Av",
                    "G30": "Broadway",
                    "G31": "Flushing Av",
                    "G32": "Myrtle-Willoughby Avs",
                    "G33": "Bedford-Nostrand Avs",
                    "G34": "Classon Av",
                    "G35": "Clinton-Washington Avs",
                    "G36": "Fulton St",
                }
                self.name_to_index = {
                    "15 St-Prospect Park": 2,
                    "21 St": 19,
                    "4 Av-9 St": 4,
                    "7 Av": 3,
                    "Bedford-Nostrand Avs": 12,
                    "Bergen St": 7,
                    "Broadway": 15,
                    "Carroll St": 6,
                    "Church Av": 0,
                    "Classon Av": 11,
                    "Clinton-Washington Avs": 10,
                    "Court Sq": 20,
                    "Flushing Av": 14,
                    "Fort Hamilton Pkwy": 1,
                    "Fulton St": 9,
                    "Greenpoint Av": 18,
                    "Hoyt-Schermerhorn Sts": 8,
                    "Metropolitan Av": 16,
                    "Myrtle-Willoughby Avs": 13,
                    "Nassau Av": 17,
                    "Smith-9 Sts": 5,
                }
            case 'GS':
                self.stop_id_to_name = {
                    "901": "Grand Central-42 St",
                    "902": "Times Sq-42 St",
                }
                self.name_to_index = {
                    "Grand Central-42 St": 1,
                    "Times Sq-42 St": 0,
                }
            case 'H':
                self.stop_id_to_name = {
                    "H04": "Broad Channel",
                    "H12": "Beach 90 St",
                    "H13": "Beach 98 St",
                    "H14": "Beach 105 St",
                    "H15": "Rockaway Park-Beach 116 St",
                }
                self.name_to_index = {
                    "Beach 105 St": 1,
                    "Beach 90 St": 3,
                    "Beach 98 St": 2,
                    "Broad Channel": 4,
                    "Rockaway Park-Beach 116 St": 0,
                }
            case 'J':
                self.stop_id_to_name = {
                    "G05": "Jamaica Center-Parsons/Archer",
                    "G06": "Sutphin Blvd-Archer Av-JFK Airport",
                    "J12": "121 St",
                    "J13": "111 St",
                    "J14": "104 St",
                    "J15": "Woodhaven Blvd",
                    "J16": "85 St-Forest Pkwy",
                    "J17": "75 St-Elderts Ln",
                    "J19": "Cypress Hills",
                    "J20": "Crescent St",
                    "J21": "Norwood Av",
                    "J22": "Cleveland St",
                    "J23": "Van Siclen Av",
                    "J24": "Alabama Av",
                    "J27": "Broadway Junction",
                    "J28": "Chauncey St",
                    "J29": "Halsey St",
                    "J30": "Gates Av",
                    "J31": "Kosciuszko St",
                    "M11": "Myrtle Av",
                    "M12": "Flushing Av",
                    "M13": "Lorimer St",
                    "M14": "Hewes St",
                    "M16": "Marcy Av",
                    "M18": "Delancey St-Essex St",
                    "M19": "Bowery",
                    "M20": "Canal St",
                    "M21": "Chambers St",
                    "M22": "Fulton St",
                    "M23": "Broad St",
                }
                self.name_to_index = {
                    "104 St": 25,
                    "111 St": 26,
                    "121 St": 27,
                    "75 St-Elderts Ln": 22,
                    "85 St-Forest Pkwy": 23,
                    "Alabama Av": 16,
                    "Bowery": 4,
                    "Broad St": 0,
                    "Broadway Junction": 15,
                    "Canal St": 3,
                    "Chambers St": 2,
                    "Chauncey St": 14,
                    "Cleveland St": 18,
                    "Crescent St": 20,
                    "Cypress Hills": 21,
                    "Delancey St-Essex St": 5,
                    "Flushing Av": 9,
                    "Fulton St": 1,
                    "Gates Av": 12,
                    "Halsey St": 13,
                    "Hewes St": 7,
                    "Jamaica Center-Parsons/Archer": 29,
                    "Kosciuszko St": 11,
                    "Lorimer St": 8,
                    "Marcy Av": 6,
                    "Myrtle Av": 10,
                    "Norwood Av": 19,
                    "Sutphin Blvd-Archer Av-JFK Airport": 28,
                    "Van Siclen Av": 17,
                    "Woodhaven Blvd": 24,
                }
            case 'L':
                self.stop_id_to_name = {
                    "L01": "8 Av",
                    "L02": "6 Av",
                    "L03": "14 St-Union Sq",
                    "L05": "3 Av",
                    "L06": "1 Av",
                    "L08": "Bedford Av",
                    "L10": "Lorimer St",
                    "L11": "Graham Av",
                    "L12": "Grand St",
                    "L13": "Montrose Av",
                    "L14": "Morgan Av",
                    "L15": "Jefferson St",
                    "L16": "DeKalb Av",
                    "L17": "Myrtle-Wyckoff Avs",
                    "L19": "Halsey St",
                    "L20": "Wilson Av",
                    "L21": "Bushwick Av-Aberdeen St",
                    "L22": "Broadway Junction",
                    "L24": "Atlantic Av",
                    "L25": "Sutter Av",
                    "L26": "Livonia Av",
                    "L27": "New Lots Av",
                    "L28": "East 105 St",
                    "L29": "Canarsie-Rockaway Pkwy",
                }
                self.name_to_index = {
                    "1 Av": 4,
                    "14 St-Union Sq": 2,
                    "3 Av": 3,
                    "6 Av": 1,
                    "8 Av": 0,
                    "Atlantic Av": 18,
                    "Bedford Av": 5,
                    "Broadway Junction": 17,
                    "Bushwick Av-Aberdeen St": 16,
                    "Canarsie-Rockaway Pkwy": 23,
                    "DeKalb Av": 12,
                    "East 105 St": 22,
                    "Graham Av": 7,
                    "Grand St": 8,
                    "Halsey St": 14,
                    "Jefferson St": 11,
                    "Livonia Av": 20,
                    "Lorimer St": 6,
                    "Montrose Av": 9,
                    "Morgan Av": 10,
                    "Myrtle-Wyckoff Avs": 13,
                    "New Lots Av": 21,
                    "Sutter Av": 19,
                    "Wilson Av": 15,
                }
            case 'M':
                self.stop_id_to_name = {
                    "D15": "47-50 Sts-Rockefeller Ctr",
                    "D16": "42 St-Bryant Pk",
                    "D17": "34 St-Herald Sq",
                    "D18": "23 St",
                    "D19": "14 St",
                    "D20": "W 4 St-Wash Sq",
                    "D21": "Broadway-Lafayette St",
                    "F09": "Court Sq-23 St",
                    "F11": "Lexington Av/53 St",
                    "F12": "5 Av/53 St",
                    "G08": "Forest Hills-71 Av",
                    "G09": "67 Av",
                    "G10": "63 Dr-Rego Park",
                    "G11": "Woodhaven Blvd",
                    "G12": "Grand Av-Newtown",
                    "G13": "Elmhurst Av",
                    "G14": "Jackson Hts-Roosevelt Av",
                    "G15": "65 St",
                    "G16": "Northern Blvd",
                    "G18": "46 St",
                    "G19": "Steinway St",
                    "G20": "36 St",
                    "G21": "Queens Plaza",
                    "M01": "Middle Village-Metropolitan Av",
                    "M04": "Fresh Pond Rd",
                    "M05": "Forest Av",
                    "M06": "Seneca Av",
                    "M08": "Myrtle-Wyckoff Avs",
                    "M09": "Knickerbocker Av",
                    "M10": "Central Av",
                    "M11": "Myrtle Av",
                    "M12": "Flushing Av",
                    "M13": "Lorimer St",
                    "M14": "Hewes St",
                    "M16": "Marcy Av",
                    "M18": "Delancey St-Essex St",
                }
                self.name_to_index = {
                    "14 St": 15,
                    "23 St": 16,
                    "34 St-Herald Sq": 17,
                    "36 St": 24,
                    "42 St-Bryant Pk": 18,
                    "46 St": 26,
                    "47-50 Sts-Rockefeller Ctr": 19,
                    "5 Av/53 St": 20,
                    "63 Dr-Rego Park": 33,
                    "65 St": 28,
                    "67 Av": 34,
                    "Broadway-Lafayette St": 13,
                    "Central Av": 6,
                    "Court Sq-23 St": 22,
                    "Delancey St-Essex St": 12,
                    "Elmhurst Av": 30,
                    "Flushing Av": 8,
                    "Forest Av": 2,
                    "Forest Hills-71 Av": 35,
                    "Fresh Pond Rd": 1,
                    "Grand Av-Newtown": 31,
                    "Hewes St": 10,
                    "Jackson Hts-Roosevelt Av": 29,
                    "Knickerbocker Av": 5,
                    "Lexington Av/53 St": 21,
                    "Lorimer St": 9,
                    "Marcy Av": 11,
                    "Middle Village-Metropolitan Av": 0,
                    "Myrtle Av": 7,
                    "Myrtle-Wyckoff Avs": 4,
                    "Northern Blvd": 27,
                    "Queens Plaza": 23,
                    "Seneca Av": 3,
                    "Steinway St": 25,
                    "W 4 St-Wash Sq": 14,
                    "Woodhaven Blvd": 32,
                }
            case 'N':
                self.stop_id_to_name = {
                    "D43": "Coney Island-Stillwell Av",
                    "N02": "8 Av",
                    "N03": "Fort Hamilton Pkwy",
                    "N04": "New Utrecht Av",
                    "N05": "18 Av",
                    "N06": "20 Av",
                    "N07": "Bay Pkwy",
                    "N08": "Kings Hwy",
                    "N09": "Avenue U",
                    "N10": "86 St",
                    "R01": "Astoria-Ditmars Blvd",
                    "R03": "Astoria Blvd",
                    "R04": "30 Av",
                    "R05": "Broadway",
                    "R06": "36 Av",
                    "R08": "39 Av-Dutch Kills",
                    "R09": "Queensboro Plaza",
                    "R11": "Lexington Av/59 St",
                    "R13": "5 Av/59 St",
                    "R14": "57 St-7 Av",
                    "R15": "49 St",
                    "R16": "Times Sq-42 St",
                    "R17": "34 St-Herald Sq",
                    "R18": "28 St",
                    "R19": "23 St",
                    "R20": "14 St-Union Sq",
                    "R21": "8 St-NYU",
                    "R22": "Prince St",
                    "R23": "Canal St",
                    "R24": "City Hall",
                    "R25": "Cortlandt St",
                    "R26": "Rector St",
                    "R27": "Whitehall St-South Ferry",
                    "R28": "Court St",
                    "R29": "Jay St-MetroTech",
                    "R30": "DeKalb Av",
                    "R31": "Atlantic Av-Barclays Ctr",
                    "R32": "Union St",
                    "R33": "4 Av-9 St",
                    "R34": "Prospect Av",
                    "R35": "25 St",
                    "R36": "36 St",
                    "R39": "45 St",
                    "R40": "53 St",
                    "R41": "59 St",
                }
                self.name_to_index = {
                    "14 St-Union Sq": 29,
                    "18 Av": 6,
                    "20 Av": 5,
                    "23 St": 30,
                    "25 St": 14,
                    "28 St": 31,
                    "30 Av": 42,
                    "34 St-Herald Sq": 32,
                    "36 Av": 40,
                    "36 St": 13,
                    "39 Av-Dutch Kills": 39,
                    "4 Av-9 St": 16,
                    "45 St": 12,
                    "49 St": 34,
                    "5 Av/59 St": 36,
                    "53 St": 11,
                    "57 St-7 Av": 35,
                    "59 St": 10,
                    "8 Av": 9,
                    "8 St-NYU": 28,
                    "86 St": 1,
                    "Astoria Blvd": 43,
                    "Astoria-Ditmars Blvd": 44,
                    "Atlantic Av-Barclays Ctr": 18,
                    "Avenue U": 2,
                    "Bay Pkwy": 4,
                    "Broadway": 41,
                    "Canal St": 26,
                    "City Hall": 25,
                    "Coney Island-Stillwell Av": 0,
                    "Cortlandt St": 24,
                    "Court St": 21,
                    "DeKalb Av": 19,
                    "Fort Hamilton Pkwy": 8,
                    "Jay St-MetroTech": 20,
                    "Kings Hwy": 3,
                    "Lexington Av/59 St": 37,
                    "New Utrecht Av": 7,
                    "Prince St": 27,
                    "Prospect Av": 15,
                    "Queensboro Plaza": 38,
                    "Rector St": 23,
                    "Times Sq-42 St": 33,
                    "Union St": 17,
                    "Whitehall St-South Ferry": 22,
                }
            case 'Q':
                self.stop_id_to_name = {
                    "B08": "Lexington Av/63 St",
                    "D24": "Atlantic Av-Barclays Ctr",
                    "D25": "7 Av",
                    "D26": "Prospect Park",
                    "D27": "Parkside Av",
                    "D28": "Church Av",
                    "D29": "Beverley Rd",
                    "D30": "Cortelyou Rd",
                    "D31": "Newkirk Plaza",
                    "D32": "Avenue H",
                    "D33": "Avenue J",
                    "D34": "Avenue M",
                    "D35": "Kings Hwy",
                    "D37": "Avenue U",
                    "D38": "Neck Rd",
                    "D39": "Sheepshead Bay",
                    "D40": "Brighton Beach",
                    "D41": "Ocean Pkwy",
                    "D42": "W 8 St-NY Aquarium",
                    "D43": "Coney Island-Stillwell Av",
                    "Q01": "Canal St",
                    "Q03": "72 St",
                    "Q04": "86 St",
                    "Q05": "96 St",
                    "R14": "57 St-7 Av",
                    "R15": "49 St",
                    "R16": "Times Sq-42 St",
                    "R17": "34 St-Herald Sq",
                    "R18": "28 St",
                    "R19": "23 St",
                    "R20": "14 St-Union Sq",
                    "R21": "8 St-NYU",
                    "R22": "Prince St",
                    "R30": "DeKalb Av",
                }
                self.name_to_index = {
                    "14 St-Union Sq": 23,
                    "23 St": 24,
                    "28 St": 25,
                    "34 St-Herald Sq": 26,
                    "49 St": 28,
                    "57 St-7 Av": 29,
                    "7 Av": 17,
                    "72 St": 31,
                    "8 St-NYU": 22,
                    "86 St": 32,
                    "96 St": 33,
                    "Atlantic Av-Barclays Ctr": 18,
                    "Avenue H": 10,
                    "Avenue J": 9,
                    "Avenue M": 8,
                    "Avenue U": 6,
                    "Beverley Rd": 13,
                    "Brighton Beach": 3,
                    "Canal St": 20,
                    "Church Av": 14,
                    "Coney Island-Stillwell Av": 0,
                    "Cortelyou Rd": 12,
                    "DeKalb Av": 19,
                    "Kings Hwy": 7,
                    "Lexington Av/63 St": 30,
                    "Neck Rd": 5,
                    "Newkirk Plaza": 11,
                    "Ocean Pkwy": 2,
                    "Parkside Av": 15,
                    "Prince St": 21,
                    "Prospect Park": 16,
                    "Sheepshead Bay": 4,
                    "Times Sq-42 St": 27,
                    "W 8 St-NY Aquarium": 1,
                }
            case 'R':
                self.stop_id_to_name = {
                    "G08": "Forest Hills-71 Av",
                    "G09": "67 Av",
                    "G10": "63 Dr-Rego Park",
                    "G11": "Woodhaven Blvd",
                    "G12": "Grand Av-Newtown",
                    "G13": "Elmhurst Av",
                    "G14": "Jackson Hts-Roosevelt Av",
                    "G15": "65 St",
                    "G16": "Northern Blvd",
                    "G18": "46 St",
                    "G19": "Steinway St",
                    "G20": "36 St",
                    "G21": "Queens Plaza",
                    "R11": "Lexington Av/59 St",
                    "R13": "5 Av/59 St",
                    "R14": "57 St-7 Av",
                    "R15": "49 St",
                    "R16": "Times Sq-42 St",
                    "R17": "34 St-Herald Sq",
                    "R18": "28 St",
                    "R19": "23 St",
                    "R20": "14 St-Union Sq",
                    "R21": "8 St-NYU",
                    "R22": "Prince St",
                    "R23": "Canal St",
                    "R24": "City Hall",
                    "R25": "Cortlandt St",
                    "R26": "Rector St",
                    "R27": "Whitehall St-South Ferry",
                    "R28": "Court St",
                    "R29": "Jay St-MetroTech",
                    "R30": "DeKalb Av",
                    "R31": "Atlantic Av-Barclays Ctr",
                    "R32": "Union St",
                    "R33": "4 Av-9 St",
                    "R34": "Prospect Av",
                    "R35": "25 St",
                    "R36": "36 St",
                    "R39": "45 St",
                    "R40": "53 St",
                    "R41": "59 St",
                    "R42": "Bay Ridge Av",
                    "R43": "77 St",
                    "R44": "86 St",
                    "R45": "Bay Ridge-95 St",
                }
                self.name_to_index = {
                    "14 St-Union Sq": 21,
                    "23 St": 20,
                    "25 St": 36,
                    "28 St": 19,
                    "34 St-Herald Sq": 18,
                    "36 St": 37,
                    "4 Av-9 St": 34,
                    "45 St": 38,
                    "46 St": 9,
                    "49 St": 16,
                    "5 Av/59 St": 14,
                    "53 St": 39,
                    "57 St-7 Av": 15,
                    "59 St": 40,
                    "63 Dr-Rego Park": 2,
                    "65 St": 7,
                    "67 Av": 1,
                    "77 St": 42,
                    "8 St-NYU": 22,
                    "86 St": 43,
                    "Atlantic Av-Barclays Ctr": 32,
                    "Bay Ridge Av": 41,
                    "Bay Ridge-95 St": 44,
                    "Canal St": 24,
                    "City Hall": 25,
                    "Cortlandt St": 26,
                    "Court St": 29,
                    "DeKalb Av": 31,
                    "Elmhurst Av": 5,
                    "Forest Hills-71 Av": 0,
                    "Grand Av-Newtown": 4,
                    "Jackson Hts-Roosevelt Av": 6,
                    "Jay St-MetroTech": 30,
                    "Lexington Av/59 St": 13,
                    "Northern Blvd": 8,
                    "Prince St": 23,
                    "Prospect Av": 35,
                    "Queens Plaza": 12,
                    "Rector St": 27,
                    "Steinway St": 10,
                    "Times Sq-42 St": 17,
                    "Union St": 33,
                    "Whitehall St-South Ferry": 28,
                    "Woodhaven Blvd": 3,
                }
            case 'SI':
                self.stop_id_to_name = {
                    "S09": "Tottenville",
                    "S11": "Arthur Kill",
                    "S13": "Richmond Valley",
                    "S14": "Pleasant Plains",
                    "S15": "Prince's Bay",
                    "S16": "Huguenot",
                    "S17": "Annadale",
                    "S18": "Eltingville",
                    "S19": "Great Kills",
                    "S20": "Bay Terrace",
                    "S21": "Oakwood Heights",
                    "S22": "New Dorp",
                    "S23": "Grant City",
                    "S24": "Jefferson Av",
                    "S25": "Dongan Hills",
                    "S26": "Old Town",
                    "S27": "Grasmere",
                    "S28": "Clifton",
                    "S29": "Stapleton",
                    "S30": "Tompkinsville",
                    "S31": "St George",
                }
                self.name_to_index = {
                    "Annadale": 6,
                    "Arthur Kill": 1,
                    "Bay Terrace": 9,
                    "Clifton": 17,
                    "Dongan Hills": 14,
                    "Eltingville": 7,
                    "Grant City": 12,
                    "Grasmere": 16,
                    "Great Kills": 8,
                    "Huguenot": 5,
                    "Jefferson Av": 13,
                    "New Dorp": 11,
                    "Oakwood Heights": 10,
                    "Old Town": 15,
                    "Pleasant Plains": 3,
                    "Prince's Bay": 4,
                    "Richmond Valley": 2,
                    "St George": 20,
                    "Stapleton": 18,
                    "Tompkinsville": 19,
                    "Tottenville": 0,
                }
            case 'W':
                self.stop_id_to_name = {
                    "N02": "8 Av",
                    "N03": "Fort Hamilton Pkwy",
                    "N04": "New Utrecht Av",
                    "N05": "18 Av",
                    "N06": "20 Av",
                    "N07": "Bay Pkwy",
                    "N08": "Kings Hwy",
                    "N09": "Avenue U",
                    "N10": "86 St",
                    "R01": "Astoria-Ditmars Blvd",
                    "R03": "Astoria Blvd",
                    "R04": "30 Av",
                    "R05": "Broadway",
                    "R06": "36 Av",
                    "R08": "39 Av-Dutch Kills",
                    "R09": "Queensboro Plaza",
                    "R11": "Lexington Av/59 St",
                    "R13": "5 Av/59 St",
                    "R14": "57 St-7 Av",
                    "R15": "49 St",
                    "R16": "Times Sq-42 St",
                    "R17": "34 St-Herald Sq",
                    "R18": "28 St",
                    "R19": "23 St",
                    "R20": "14 St-Union Sq",
                    "R21": "8 St-NYU",
                    "R22": "Prince St",
                    "R23": "Canal St",
                    "R24": "City Hall",
                    "R25": "Cortlandt St",
                    "R26": "Rector St",
                    "R27": "Whitehall St-South Ferry",
                    "R28": "Court St",
                    "R29": "Jay St-MetroTech",
                    "R30": "DeKalb Av",
                    "R31": "Atlantic Av-Barclays Ctr",
                    "R32": "Union St",
                    "R33": "4 Av-9 St",
                    "R34": "Prospect Av",
                    "R41": "59 St",
                }
                self.name_to_index = {
                    "14 St-Union Sq": 15,
                    "18 Av": 38,
                    "20 Av": 39,
                    "23 St": 14,
                    "25 St": 30,
                    "28 St": 13,
                    "30 Av": 2,
                    "34 St-Herald Sq": 12,
                    "36 Av": 4,
                    "36 St": 31,
                    "39 Av-Dutch Kills": 5,
                    "4 Av-9 St": 28,
                    "45 St": 32,
                    "49 St": 10,
                    "5 Av/59 St": 8,
                    "53 St": 33,
                    "57 St-7 Av": 9,
                    "59 St": 34,
                    "8 Av": 35,
                    "8 St-NYU": 16,
                    "86 St": 43,
                    "Astoria Blvd": 1,
                    "Astoria-Ditmars Blvd": 0,
                    "Atlantic Av-Barclays Ctr": 26,
                    "Avenue U": 42,
                    "Bay Pkwy": 40,
                    "Broadway": 3,
                    "Canal St": 18,
                    "City Hall": 19,
                    "Cortlandt St": 20,
                    "Court St": 23,
                    "DeKalb Av": 25,
                    "Fort Hamilton Pkwy": 36,
                    "Jay St-MetroTech": 24,
                    "Kings Hwy": 41,
                    "Lexington Av/59 St": 7,
                    "New Utrecht Av": 37,
                    "Prince St": 17,
                    "Prospect Av": 29,
                    "Queensboro Plaza": 6,
                    "Rector St": 21,
                    "Times Sq-42 St": 11,
                    "Union St": 27,
                    "Whitehall St-South Ferry": 22,
                }
            case 'Z':
                self.stop_id_to_name = {
                    "G05": "Jamaica Center-Parsons/Archer",
                    "G06": "Sutphin Blvd-Archer Av-JFK Airport",
                    "J12": "121 St",
                    "J14": "104 St",
                    "J15": "Woodhaven Blvd",
                    "J17": "75 St-Elderts Ln",
                    "J20": "Crescent St",
                    "J21": "Norwood Av",
                    "J23": "Van Siclen Av",
                    "J24": "Alabama Av",
                    "J27": "Broadway Junction",
                    "J28": "Chauncey St",
                    "J30": "Gates Av",
                    "M11": "Myrtle Av",
                    "M16": "Marcy Av",
                    "M18": "Delancey St-Essex St",
                    "M19": "Bowery",
                    "M20": "Canal St",
                    "M21": "Chambers St",
                    "M22": "Fulton St",
                    "M23": "Broad St",
                }
                self.name_to_index = {
                    "104 St": 17,
                    "121 St": 18,
                    "75 St-Elderts Ln": 15,
                    "Alabama Av": 11,
                    "Bowery": 4,
                    "Broad St": 0,
                    "Broadway Junction": 10,
                    "Canal St": 3,
                    "Chambers St": 2,
                    "Chauncey St": 9,
                    "Crescent St": 14,
                    "Delancey St-Essex St": 5,
                    "Fulton St": 1,
                    "Gates Av": 8,
                    "Jamaica Center-Parsons/Archer": 20,
                    "Marcy Av": 6,
                    "Myrtle Av": 7,
                    "Norwood Av": 13,
                    "Sutphin Blvd-Archer Av-JFK Airport": 19,
                    "Van Siclen Av": 12,
                    "Woodhaven Blvd": 16,
                }

        # precompute helpers
        self.station_names = list(self.name_to_index.keys())
        self.line_directions = directions[args.route]
        self.endpoint_name = (max(self.name_to_index, key=self.name_to_index.get)
                              if isinstance(self.line_directions[1], int)
                              else self.line_directions[1])
        self._trip_direction_map = None

    def station_id_to_name(self, stop_id: str) -> Optional[str]:
        return self.stop_id_to_name.get(stop_id)

    def station_name_to_index(self, name: str) -> Optional[int]:
        return self.name_to_index.get(name)

    def get_trains(self, feed: gtfs_realtime_pb2.FeedMessage) -> List[Train]:
        trip_updates = {}
        vehicles = {}
        for entity in feed.entity:
            if entity.HasField('trip_update'):
                try:
                    trip = entity.trip_update.trip
                    trip_id = getattr(trip, "trip_id", None)
                    route_id = getattr(trip, "route_id", None)
                    if trip_id and route_id == args.route:
                        trip_updates[trip_id] = entity.trip_update
                except Exception:
                    continue
            if entity.HasField('vehicle'):
                try:
                    veh_trip = entity.vehicle.trip
                    veh_trip_id = getattr(veh_trip, "trip_id", None)
                    if veh_trip_id:
                        vehicles[veh_trip_id] = entity.vehicle
                except Exception:
                    continue

        trains: List[Train] = []
        for trip_id, tu in trip_updates.items():
            try:
                route_id = tu.trip.route_id
            except Exception:
                continue
            if route_id != args.route:
                continue

            next_stop_id = "(no stop)"
            arrival_ts = None
            for stu in tu.stop_time_update:
                at = getattr(stu, "arrival", None)
                dt = getattr(stu, "departure", None)
                if at and getattr(at, "time", 0):
                    arrival_ts = getattr(at, "time")
                    next_stop_id = getattr(stu, "stop_id", "(no stop)")
                    break
                if dt and getattr(dt, "time", 0):
                    arrival_ts = getattr(dt, "time")
                    next_stop_id = getattr(stu, "stop_id", "(no stop)")
                    break

            secs = _secs_until(arrival_ts) if arrival_ts else 0.0

            direction_char = None
            if len(next_stop_id) > 1 and next_stop_id[-1] in ('N', 'S'):
                direction_char = next_stop_id[-1]

            direction = None
            try:
                direction = tu.trip.direction_id
            except Exception:
                pass

            veh = vehicles.get(trip_id)
            veh_stop = None
            status = None
            if veh:
                try:
                    veh_stop = veh.stop_id if hasattr(veh, "stop_id") else None
                except Exception:
                    veh_stop = None
                try:
                    status = gtfs_realtime_pb2.VehiclePosition.VehicleStopStatus.Name(veh.current_status)
                except Exception:
                    status = str(getattr(veh, "current_status", ""))

            base_stop_id = next_stop_id[:-1] if direction_char else next_stop_id
            station_name = self.station_id_to_name(base_stop_id)
            station_index = self.station_name_to_index(station_name) if station_name else -1

            trains.append(Train(
                trip_id=trip_id,
                route_id=route_id,
                start_date=tu.trip.start_date if hasattr(tu.trip, "start_date") else "",
                next_stop_id=next_stop_id,
                time_until=secs,
                direction=direction,
                next_station_index=station_index,
                direction_char=direction_char,
                vehicle_stop_id=veh_stop,
                current_status=status
            ))

        def get_sort_key(train: Train):
            # Direction 0 is typically 'North' or towards the higher-indexed station
            is_to_endpoint = (train.direction_char == 'N')
            
            # Primary sort: station index.
            # We want descending for trains going towards the endpoint (higher index),
            # and ascending for trains going away from it.
            # Adding a boolean `is_to_endpoint` achieves this.
            primary_sort = -train.next_station_index + is_to_endpoint

            # Secondary sort: trip start time, to group trains on the same block
            try:
                secondary_sort = int(train.trip_id.split('_')[0])
            except (ValueError, IndexError):
                secondary_sort = 0
            
            # Invert secondary sort based on direction to maintain order within a block
            secondary_sort *= (1 if is_to_endpoint else -1)

            return (primary_sort, secondary_sort)

        try:
            trains = sorted(trains, key=get_sort_key)
        except Exception:
            pass
        
        return trains

def self_test():
    print("NYC MTA Subway Routes:\n")
    for route in route_ids:
        color = colors.get(route, "\033[0m")
        print(f"{color}{route}: {line_to_long_name[route]}\033[0m")
    print("\n")
    print(len(route_ids), "routes total.")
    print(len(line_to_long_name), "long names total.")
    print(len(colors), "ANSI colors total.")
    print(len(line_to_url), "line to URL mappings total.")

if __name__ == "__main__":
    if args.self_test:
        self_test()
        exit()

    if args.route:
        traingetter = TrainGetter() # Instantiate the class
        feed = gtfs_realtime_pb2.FeedMessage()
        url = line_to_url[args.route]
        
        try:
            response = requests.get(url)
            response.raise_for_status()
            feed.ParseFromString(response.content)
        except requests.exceptions.RequestException as e:
            print(f"Error fetching data: {e}")
            exit()

        trains = traingetter.get_trains(feed)

        # Print the results
        color = colors.get(args.route, "\033[0m")
        print(color + f" {args.route}: {line_to_long_name.get(args.route, '')} " + "\033[0m")
        if not trains:
            print("No trip updates for this route in feed.")
        else:
            for t in trains:
                print(t)